# Generated by Django 5.1.6 on 2025-03-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel_owners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=400)),
                (
                    "hotel_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_owners.hotelowner",
                    ),
                ),
            ],
        ),
    ]
