# Generated by Django 5.1.7 on 2025-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_hotelimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(
                error_messages={
                    "unique": "El nombre del hotel ya está en uso. Por favor, elige otro."
                },
                max_length=100,
                unique=True,
            ),
        ),
    ]
