# Generated by Django 5.1.6 on 2025-03-16 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_types", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="num_rooms",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ]
            ),
        ),
    ]
