# Generated by Django 5.1.6 on 2025-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_types", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="pet_type",
            field=models.CharField(
                choices=[
                    ("DOG", "Dog"),
                    ("CAT", "Cat"),
                    ("BIRD", "Bird"),
                    ("MIXED", "Mixed"),
                ],
                max_length=30,
            ),
        ),
    ]
