# Generated by Django 5.1.7 on 2025-05-03 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_types", "0002_roomtype_num_rooms_alter_roomtype_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="num_rooms",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
    ]
