# Generated by Django 5.1.6 on 2025-03-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_alter_customer_user"),
        ("room_types", "0002_roomtype_num_rooms_alter_roomtype_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hold_expires_at", models.DateTimeField()),
                ("booking_start_date", models.DateField()),
                ("booking_end_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room_types.roomtype",
                    ),
                ),
            ],
        ),
    ]
