# Generated by Django 5.1.6 on 2025-03-16 21:49

import django.db.models.deletion
import pawtel.booking_holds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("room_types", "0002_roomtype_num_rooms_alter_roomtype_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hold_expires_at",
                    models.DateTimeField(
                        default=pawtel.booking_holds.models.default_hold_expiry
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room_types.roomtype",
                    ),
                ),
            ],
        ),
    ]
