# Generated by Django 5.1.7 on 2025-04-29 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="paw_points",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
