import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).fill('hotelowne2');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('password123');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).fill('hotelowne2');
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).fill('hotelowner2');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.goto("http://localhost:5173/mis-hoteles?filterCity=&filterType&filterStartDate&filterEndDate");
  await page.getByRole('button', { name: ' Editar' }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Nombre del hotel$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Nombre del hotel$/ }).getByRole('textbox').fill('Pla y Viña S.AA.');
  await page.locator('div').filter({ hasText: /^Dirección$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Dirección$/ }).getByRole('textbox').press('ArrowRight');
  await page.locator('div').filter({ hasText: /^Dirección$/ }).getByRole('textbox').press('ArrowRight');
  await page.locator('div').filter({ hasText: /^Dirección$/ }).getByRole('textbox').press('ArrowRight');
  await page.locator('div').filter({ hasText: /^Dirección$/ }).getByRole('textbox').fill('Camino Samuel Falcón 51');
  await page.locator('div').filter({ hasText: /^Ciudad$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Ciudad$/ }).getByRole('textbox').fill('Almería');
  await page.getByRole('button', { name: ' Guardar cambios' }).click();
  await page.getByRole('button', { name: ' Añadir nueva habitación' }).click();
  await page.locator('div').filter({ hasText: /^Nombre:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Nombre:$/ }).getByRole('textbox').fill('Habitación Playwright');
  await page.locator('div').filter({ hasText: /^Descripción:$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^Descripción:$/ }).getByRole('textbox').fill('Prueba de video');
  await page.locator('div').filter({ hasText: /^Capacidad:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Capacidad:$/ }).getByRole('spinbutton').fill('13');
  await page.locator('div').filter({ hasText: /^Precio por noche:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Precio por noche:$/ }).getByRole('spinbutton').fill('11');
  await page.locator('div').filter({ hasText: /^Número de habitaciones:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Número de habitaciones:$/ }).getByRole('spinbutton').fill('5');
  await page.getByRole('combobox').selectOption('BIRD');
  await page.getByRole('button', { name: ' Añadir Habitación' }).click();
  await page.locator('div:nth-child(5) > div:nth-child(2)').first().click();
  await page.getByRole('button', { name: ' Editar' }).nth(4).click();
  await page.locator('div').filter({ hasText: /^Número de habitaciones:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Número de habitaciones:$/ }).getByRole('spinbutton').fill('7');
  await page.getByRole('button', { name: ' Guardar cambios' }).nth(1).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: ' Eliminar' }).nth(4).click();
  await page.getByRole('img', { name: 'Imagen del hotel 2' }).click();
  await page.getByRole('img', { name: 'Imagen del hotel 3' }).click();
  await page.locator('div:nth-child(3) > div > .bg-gray-800').click();
  await page.getByRole('button', { name: 'Portada' }).click();
  await page.locator('.bg-gray-800').first().click();
  await page.getByRole('button', { name: 'Portada' }).click();
});