# Generated by Django 5.1.3 on 2025-03-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_users.appuser",
                    ),
                ),
            ],
        ),
    ]
