# Generated by Django 5.1.6 on 2025-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_owners", "0002_alter_hotelowner_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelowner",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
