# Generated by Django 5.1.7 on 2025-04-07 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_termsacceptance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="phone",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de teleéfono debe ser del formato: +34XXXXXXXXX",
                        regex="^\\+34\\d{9}$",
                    )
                ],
            ),
        ),
    ]
